### ISSUE TITLE
你好，有没有具体的gulp 集成的gulpfile 的example啊，只看片段代码看不懂

### ISSUE THREAD

**Issue by yytian1017** [princetoad/postcss-less2scss#1]

**Comment by princetoad** [comment]
> https://github.com/princetoad/try-postcss/blob/master/gulpfile.js


这个文件中的 less2scss 这个 task 执行的就是调用 postcss-less2scss 进行 Less 转换工作的，你可以把 try-postcss 这个项目下载下来，然后跑一下这个 task 试试。在项目根目录下运行 `npx gulp less2scss` 命令即可。
